---
- hosts: 127.0.0.1
  connection: local
  tasks:
   - name: install traceroute
     command: sudo apt-get install traceroute -y
   - name: install updates
     command: sudo apt-get update && sudo apt-get upgrade -y